# syntax=docker/dockerfile:1

FROM golang:1.18-alpine

ENV TYCOON_KEY_PRIVATE=blah
ENV MONGO_URI=blah
ENV DB_TITLE=Tycoon

WORKDIR /app

COPY * ./

RUN ["chmod", "+x", "./tt-scraper"]
CMD [ "./tt-scraper"]
